export const countryList = [
  {
    cca2: 'AW',
    country: 'Aruba',
    flag: '🇦🇼',
    countryRus: 'Аруба',
  },
  {
    cca2: 'AF',
    country: 'Afghanistan',
    flag: '🇦🇫',
    countryRus: 'Афганистан',
  },
  {
    cca2: 'AO',
    country: 'Angola',
    flag: '🇦🇴',
    countryRus: 'Ангола',
  },
  {
    cca2: 'AI',
    country: 'Anguilla',
    flag: '🇦🇮',
    countryRus: 'Ангилья',
  },
  {
    cca2: 'AX',
    country: 'Åland Islands',
    flag: '🇦🇽',
    countryRus: 'Аландские о-ва',
  },
  {
    cca2: 'AL',
    country: 'Albania',
    flag: '🇦🇱',
    countryRus: 'Албания',
  },
  {
    cca2: 'AD',
    country: 'Andorra',
    flag: '🇦🇩',
    countryRus: 'Андорра',
  },
  {
    cca2: 'AE',
    country: 'United Arab Emirates',
    flag: '🇦🇪',
    countryRus: 'ОАЭ',
  },
  {
    cca2: 'AR',
    country: 'Argentina',
    flag: '🇦🇷',
    countryRus: 'Аргентина',
  },
  {
    cca2: 'AM',
    country: 'Armenia',
    flag: '🇦🇲',
    countryRus: 'Армения',
  },
  {
    cca2: 'AS',
    country: 'American Samoa',
    flag: '🇦🇸',
    countryRus: 'Американское Самоа',
  },
  {
    cca2: 'AQ',
    country: 'Antarctica',
    flag: '🇦🇶',
    countryRus: 'Антарктида',
  },
  {
    cca2: 'TF',
    country: 'French Southern and Antarctic Lands',
    flag: '🇹🇫',
    countryRus: 'Французские Южные территории',
  },
  {
    cca2: 'AG',
    country: 'Antigua and Barbuda',
    flag: '🇦🇬',
    countryRus: 'Антигуа и Барбуда',
  },
  {
    cca2: 'AU',
    country: 'Australia',
    flag: '🇦🇺',
    countryRus: 'Австралия',
  },
  {
    cca2: 'AT',
    country: 'Austria',
    flag: '🇦🇹',
    countryRus: 'Австрия',
  },
  {
    cca2: 'AZ',
    country: 'Azerbaijan',
    flag: '🇦🇿',
    countryRus: 'Азербайджан',
  },
  {
    cca2: 'BI',
    country: 'Burundi',
    flag: '🇧🇮',
    countryRus: 'Бурунди',
  },
  {
    cca2: 'BE',
    country: 'Belgium',
    flag: '🇧🇪',
    countryRus: 'Бельгия',
  },
  {
    cca2: 'BJ',
    country: 'Benin',
    flag: '🇧🇯',
    countryRus: 'Бенин',
  },
  {
    cca2: 'BF',
    country: 'Burkina Faso',
    flag: '🇧🇫',
    countryRus: 'Буркина-Фасо',
  },
  {
    cca2: 'BD',
    country: 'Bangladesh',
    flag: '🇧🇩',
    countryRus: 'Бангладеш',
  },
  {
    cca2: 'BG',
    country: 'Bulgaria',
    flag: '🇧🇬',
    countryRus: 'Болгария',
  },
  {
    cca2: 'BH',
    country: 'Bahrain',
    flag: '🇧🇭',
    countryRus: 'Бахрейн',
  },
  {
    cca2: 'BS',
    country: 'Bahamas',
    flag: '🇧🇸',
    countryRus: 'Багамы',
  },
  {
    cca2: 'BA',
    country: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    countryRus: 'Босния и Герцеговина',
  },
  {
    cca2: 'BL',
    country: 'Saint Barthélemy',
    flag: '🇧🇱',
    countryRus: 'Сен-Бартелеми',
  },
  {
    cca2: 'SH',
    country: 'Saint Helena, Ascension and Tristan da Cunha',
    flag: '🇸🇭',
    countryRus: 'о-в Св. Елены',
  },
  {
    cca2: 'BY',
    country: 'Belarus',
    flag: '🇧🇾',
    countryRus: 'Беларусь',
  },
  {
    cca2: 'BZ',
    country: 'Belize',
    flag: '🇧🇿',
    countryRus: 'Белиз',
  },
  {
    cca2: 'BM',
    country: 'Bermuda',
    flag: '🇧🇲',
    countryRus: 'Бермудские о-ва',
  },
  {
    cca2: 'BO',
    country: 'Bolivia',
    flag: '🇧🇴',
    countryRus: 'Боливия',
  },
  {
    cca2: 'BQ',
    country: 'Caribbean Netherlands',
    flag: '',
    countryRus: 'Бонэйр, Синт-Эстатиус и Саба',
  },
  {
    cca2: 'BR',
    country: 'Brazil',
    flag: '🇧🇷',
    countryRus: 'Бразилия',
  },
  {
    cca2: 'BB',
    country: 'Barbados',
    flag: '🇧🇧',
    countryRus: 'Барбадос',
  },
  {
    cca2: 'BN',
    country: 'Brunei',
    flag: '🇧🇳',
    countryRus: 'Бруней',
  },
  {
    cca2: 'BT',
    country: 'Bhutan',
    flag: '🇧🇹',
    countryRus: 'Бутан',
  },
  {
    cca2: 'BV',
    country: 'Bouvet Island',
    flag: '🇧🇻',
    countryRus: 'о-в Буве',
  },
  {
    cca2: 'BW',
    country: 'Botswana',
    flag: '🇧🇼',
    countryRus: 'Ботсвана',
  },
  {
    cca2: 'CF',
    country: 'Central African Republic',
    flag: '🇨🇫',
    countryRus: 'Центрально-Африканская Республика',
  },
  {
    cca2: 'CA',
    country: 'Canada',
    flag: '🇨🇦',
    countryRus: 'Канада',
  },
  {
    cca2: 'CC',
    country: 'Cocos (Keeling) Islands',
    flag: '🇨🇨',
    countryRus: 'Кокосовые о-ва',
  },
  {
    cca2: 'CH',
    country: 'Switzerland',
    flag: '🇨🇭',
    countryRus: 'Швейцария',
  },
  {
    cca2: 'CL',
    country: 'Chile',
    flag: '🇨🇱',
    countryRus: 'Чили',
  },
  {
    cca2: 'CN',
    country: 'China',
    flag: '🇨🇳',
    countryRus: 'Китай',
  },
  {
    cca2: 'CI',
    country: 'Ivory Coast',
    flag: '🇨🇮',
    countryRus: 'Кот-д’Ивуар',
  },
  {
    cca2: 'CM',
    country: 'Cameroon',
    flag: '🇨🇲',
    countryRus: 'Камерун',
  },
  {
    cca2: 'CD',
    country: 'DR Congo',
    flag: '🇨🇩',
    countryRus: 'Конго - Киншаса',
  },
  {
    cca2: 'CG',
    country: 'Republic of the Congo',
    flag: '🇨🇬',
    countryRus: 'Конго - Браззавиль',
  },
  {
    cca2: 'CK',
    country: 'Cook Islands',
    flag: '🇨🇰',
    countryRus: 'о-ва Кука',
  },
  {
    cca2: 'CO',
    country: 'Colombia',
    flag: '🇨🇴',
    countryRus: 'Колумбия',
  },
  {
    cca2: 'KM',
    country: 'Comoros',
    flag: '🇰🇲',
    countryRus: 'Коморы',
  },
  {
    cca2: 'CV',
    country: 'Cape Verde',
    flag: '🇨🇻',
    countryRus: 'Кабо-Верде',
  },
  {
    cca2: 'CR',
    country: 'Costa Rica',
    flag: '🇨🇷',
    countryRus: 'Коста-Рика',
  },
  {
    cca2: 'CU',
    country: 'Cuba',
    flag: '🇨🇺',
    countryRus: 'Куба',
  },
  {
    cca2: 'CW',
    country: 'Curaçao',
    flag: '🇨🇼',
    countryRus: 'Кюрасао',
  },
  {
    cca2: 'CX',
    country: 'Christmas Island',
    flag: '🇨🇽',
    countryRus: 'о-в Рождества',
  },
  {
    cca2: 'KY',
    country: 'Cayman Islands',
    flag: '🇰🇾',
    countryRus: 'о-ва Кайман',
  },
  {
    cca2: 'CY',
    country: 'Cyprus',
    flag: '🇨🇾',
    countryRus: 'Кипр',
  },
  {
    cca2: 'CZ',
    country: 'Czechia',
    flag: '🇨🇿',
    countryRus: 'Чехия',
  },
  {
    cca2: 'DE',
    country: 'Germany',
    flag: '🇩🇪',
    countryRus: 'Германия',
  },
  {
    cca2: 'DJ',
    country: 'Djibouti',
    flag: '🇩🇯',
    countryRus: 'Джибути',
  },
  {
    cca2: 'DM',
    country: 'Dominica',
    flag: '🇩🇲',
    countryRus: 'Доминика',
  },
  {
    cca2: 'DK',
    country: 'Denmark',
    flag: '🇩🇰',
    countryRus: 'Дания',
  },
  {
    cca2: 'DO',
    country: 'Dominican Republic',
    flag: '🇩🇴',
    countryRus: 'Доминиканская Республика',
  },
  {
    cca2: 'DZ',
    country: 'Algeria',
    flag: '🇩🇿',
    countryRus: 'Алжир',
  },
  {
    cca2: 'EC',
    country: 'Ecuador',
    flag: '🇪🇨',
    countryRus: 'Эквадор',
  },
  {
    cca2: 'EG',
    country: 'Egypt',
    flag: '🇪🇬',
    countryRus: 'Египет',
  },
  {
    cca2: 'ER',
    country: 'Eritrea',
    flag: '🇪🇷',
    countryRus: 'Эритрея',
  },
  {
    cca2: 'EH',
    country: 'Western Sahara',
    flag: '🇪🇭',
    countryRus: 'Западная Сахара',
  },
  {
    cca2: 'ES',
    country: 'Spain',
    flag: '🇪🇸',
    countryRus: 'Испания',
  },
  {
    cca2: 'EE',
    country: 'Estonia',
    flag: '🇪🇪',
    countryRus: 'Эстония',
  },
  {
    cca2: 'ET',
    country: 'Ethiopia',
    flag: '🇪🇹',
    countryRus: 'Эфиопия',
  },
  {
    cca2: 'FI',
    country: 'Finland',
    flag: '🇫🇮',
    countryRus: 'Финляндия',
  },
  {
    cca2: 'FJ',
    country: 'Fiji',
    flag: '🇫🇯',
    countryRus: 'Фиджи',
  },
  {
    cca2: 'FK',
    country: 'Falkland Islands',
    flag: '🇫🇰',
    countryRus: 'Фолклендские (Мальвинские) о-ва',
  },
  {
    cca2: 'FR',
    country: 'France',
    flag: '🇫🇷',
    countryRus: 'Франция',
  },
  {
    cca2: 'FO',
    country: 'Faroe Islands',
    flag: '🇫🇴',
    countryRus: 'Фарерские о-ва',
  },
  {
    cca2: 'FM',
    country: 'Micronesia',
    flag: '🇫🇲',
    countryRus: 'Федеративные Штаты Микронезии',
  },
  {
    cca2: 'GA',
    country: 'Gabon',
    flag: '🇬🇦',
    countryRus: 'Габон',
  },
  {
    cca2: 'GB',
    country: 'United Kingdom',
    flag: '🇬🇧',
    countryRus: 'Великобритания',
  },
  {
    cca2: 'GE',
    country: 'Georgia',
    flag: '🇬🇪',
    countryRus: 'Грузия',
  },
  {
    cca2: 'GG',
    country: 'Guernsey',
    flag: '🇬🇬',
    countryRus: 'Гернси',
  },
  {
    cca2: 'GH',
    country: 'Ghana',
    flag: '🇬🇭',
    countryRus: 'Гана',
  },
  {
    cca2: 'GI',
    country: 'Gibraltar',
    flag: '🇬🇮',
    countryRus: 'Гибралтар',
  },
  {
    cca2: 'GN',
    country: 'Guinea',
    flag: '🇬🇳',
    countryRus: 'Гвинея',
  },
  {
    cca2: 'GP',
    country: 'Guadeloupe',
    flag: '🇬🇵',
    countryRus: 'Гваделупа',
  },
  {
    cca2: 'GM',
    country: 'Gambia',
    flag: '🇬🇲',
    countryRus: 'Гамбия',
  },
  {
    cca2: 'GW',
    country: 'Guinea-Bissau',
    flag: '🇬🇼',
    countryRus: 'Гвинея-Бисау',
  },
  {
    cca2: 'GQ',
    country: 'Equatorial Guinea',
    flag: '🇬🇶',
    countryRus: 'Экваториальная Гвинея',
  },
  {
    cca2: 'GR',
    country: 'Greece',
    flag: '🇬🇷',
    countryRus: 'Греция',
  },
  {
    cca2: 'GD',
    country: 'Grenada',
    flag: '🇬🇩',
    countryRus: 'Гренада',
  },
  {
    cca2: 'GL',
    country: 'Greenland',
    flag: '🇬🇱',
    countryRus: 'Гренландия',
  },
  {
    cca2: 'GT',
    country: 'Guatemala',
    flag: '🇬🇹',
    countryRus: 'Гватемала',
  },
  {
    cca2: 'GF',
    country: 'French Guiana',
    flag: '🇬🇫',
    countryRus: 'Французская Гвиана',
  },
  {
    cca2: 'GU',
    country: 'Guam',
    flag: '🇬🇺',
    countryRus: 'Гуам',
  },
  {
    cca2: 'GY',
    country: 'Guyana',
    flag: '🇬🇾',
    countryRus: 'Гайана',
  },
  {
    cca2: 'HK',
    country: 'Hong Kong',
    flag: '🇭🇰',
    countryRus: 'Гонконг',
  },
  {
    cca2: 'HM',
    country: 'Heard Island and McDonald Islands',
    flag: '🇭🇲',
    countryRus: 'о-ва Херд и Макдональд',
  },
  {
    cca2: 'HN',
    country: 'Honduras',
    flag: '🇭🇳',
    countryRus: 'Гондурас',
  },
  {
    cca2: 'HR',
    country: 'Croatia',
    flag: '🇭🇷',
    countryRus: 'Хорватия',
  },
  {
    cca2: 'HT',
    country: 'Haiti',
    flag: '🇭🇹',
    countryRus: 'Гаити',
  },
  {
    cca2: 'HU',
    country: 'Hungary',
    flag: '🇭🇺',
    countryRus: 'Венгрия',
  },
  {
    cca2: 'ID',
    country: 'Indonesia',
    flag: '🇮🇩',
    countryRus: 'Индонезия',
  },
  {
    cca2: 'IM',
    country: 'Isle of Man',
    flag: '🇮🇲',
    countryRus: 'о-в Мэн',
  },
  {
    cca2: 'IN',
    country: 'India',
    flag: '🇮🇳',
    countryRus: 'Индия',
  },
  {
    cca2: 'IO',
    country: 'British Indian Ocean Territory',
    flag: '🇮🇴',
    countryRus: 'Британская территория в Индийском океане',
  },
  {
    cca2: 'IE',
    country: 'Ireland',
    flag: '🇮🇪',
    countryRus: 'Ирландия',
  },
  {
    cca2: 'IR',
    country: 'Iran',
    flag: '🇮🇷',
    countryRus: 'Иран',
  },
  {
    cca2: 'IQ',
    country: 'Iraq',
    flag: '🇮🇶',
    countryRus: 'Ирак',
  },
  {
    cca2: 'IS',
    country: 'Iceland',
    flag: '🇮🇸',
    countryRus: 'Исландия',
  },
  {
    cca2: 'IL',
    country: 'Israel',
    flag: '🇮🇱',
    countryRus: 'Израиль',
  },
  {
    cca2: 'IT',
    country: 'Italy',
    flag: '🇮🇹',
    countryRus: 'Италия',
  },
  {
    cca2: 'JM',
    country: 'Jamaica',
    flag: '🇯🇲',
    countryRus: 'Ямайка',
  },
  {
    cca2: 'JE',
    country: 'Jersey',
    flag: '🇯🇪',
    countryRus: 'Джерси',
  },
  {
    cca2: 'JO',
    country: 'Jordan',
    flag: '🇯🇴',
    countryRus: 'Иордания',
  },
  {
    cca2: 'JP',
    country: 'Japan',
    flag: '🇯🇵',
    countryRus: 'Япония',
  },
  {
    cca2: 'KZ',
    country: 'Kazakhstan',
    flag: '🇰🇿',
    countryRus: 'Казахстан',
  },
  {
    cca2: 'KE',
    country: 'Kenya',
    flag: '🇰🇪',
    countryRus: 'Кения',
  },
  {
    cca2: 'KG',
    country: 'Kyrgyzstan',
    flag: '🇰🇬',
    countryRus: 'Киргизия',
  },
  {
    cca2: 'KH',
    country: 'Cambodia',
    flag: '🇰🇭',
    countryRus: 'Камбоджа',
  },
  {
    cca2: 'KI',
    country: 'Kiribati',
    flag: '🇰🇮',
    countryRus: 'Кирибати',
  },
  {
    cca2: 'KN',
    country: 'Saint Kitts and Nevis',
    flag: '🇰🇳',
    countryRus: 'Сент-Китс и Невис',
  },
  {
    cca2: 'KR',
    country: 'South Korea',
    flag: '🇰🇷',
    countryRus: 'Республика Корея',
  },
  {
    cca2: 'XK',
    country: 'Kosovo',
    flag: '🇽🇰',
    countryRus: 'Косово',
  },
  {
    cca2: 'KW',
    country: 'Kuwait',
    flag: '🇰🇼',
    countryRus: 'Кувейт',
  },
  {
    cca2: 'LA',
    country: 'Laos',
    flag: '🇱🇦',
    countryRus: 'Лаос',
  },
  {
    cca2: 'LB',
    country: 'Lebanon',
    flag: '🇱🇧',
    countryRus: 'Ливан',
  },
  {
    cca2: 'LR',
    country: 'Liberia',
    flag: '🇱🇷',
    countryRus: 'Либерия',
  },
  {
    cca2: 'LY',
    country: 'Libya',
    flag: '🇱🇾',
    countryRus: 'Ливия',
  },
  {
    cca2: 'LC',
    country: 'Saint Lucia',
    flag: '🇱🇨',
    countryRus: 'Сент-Люсия',
  },
  {
    cca2: 'LI',
    country: 'Liechtenstein',
    flag: '🇱🇮',
    countryRus: 'Лихтенштейн',
  },
  {
    cca2: 'LK',
    country: 'Sri Lanka',
    flag: '🇱🇰',
    countryRus: 'Шри-Ланка',
  },
  {
    cca2: 'LS',
    country: 'Lesotho',
    flag: '🇱🇸',
    countryRus: 'Лесото',
  },
  {
    cca2: 'LT',
    country: 'Lithuania',
    flag: '🇱🇹',
    countryRus: 'Литва',
  },
  {
    cca2: 'LU',
    country: 'Luxembourg',
    flag: '🇱🇺',
    countryRus: 'Люксембург',
  },
  {
    cca2: 'LV',
    country: 'Latvia',
    flag: '🇱🇻',
    countryRus: 'Латвия',
  },
  {
    cca2: 'MO',
    country: 'Macau',
    flag: '🇲🇴',
    countryRus: 'Макао',
  },
  {
    cca2: 'MF',
    country: 'Saint Martin',
    flag: '🇲🇫',
    countryRus: 'Сен-Мартен',
  },
  {
    cca2: 'MA',
    country: 'Morocco',
    flag: '🇲🇦',
    countryRus: 'Марокко',
  },
  {
    cca2: 'MC',
    country: 'Monaco',
    flag: '🇲🇨',
    countryRus: 'Монако',
  },
  {
    cca2: 'MD',
    country: 'Moldova',
    flag: '🇲🇩',
    countryRus: 'Молдова',
  },
  {
    cca2: 'MG',
    country: 'Madagascar',
    flag: '🇲🇬',
    countryRus: 'Мадагаскар',
  },
  {
    cca2: 'MV',
    country: 'Maldives',
    flag: '🇲🇻',
    countryRus: 'Мальдивы',
  },
  {
    cca2: 'MX',
    country: 'Mexico',
    flag: '🇲🇽',
    countryRus: 'Мексика',
  },
  {
    cca2: 'MH',
    country: 'Marshall Islands',
    flag: '🇲🇭',
    countryRus: 'Маршалловы о-ва',
  },
  {
    cca2: 'MK',
    country: 'North Macedonia',
    flag: '🇲🇰',
    countryRus: 'Северная Македония',
  },
  {
    cca2: 'ML',
    country: 'Mali',
    flag: '🇲🇱',
    countryRus: 'Мали',
  },
  {
    cca2: 'MT',
    country: 'Malta',
    flag: '🇲🇹',
    countryRus: 'Мальта',
  },
  {
    cca2: 'MM',
    country: 'Myanmar',
    flag: '🇲🇲',
    countryRus: 'Мьянма (Бирма)',
  },
  {
    cca2: 'ME',
    country: 'Montenegro',
    flag: '🇲🇪',
    countryRus: 'Черногория',
  },
  {
    cca2: 'MN',
    country: 'Mongolia',
    flag: '🇲🇳',
    countryRus: 'Монголия',
  },
  {
    cca2: 'MP',
    country: 'Northern Mariana Islands',
    flag: '🇲🇵',
    countryRus: 'Северные Марианские о-ва',
  },
  {
    cca2: 'MZ',
    country: 'Mozambique',
    flag: '🇲🇿',
    countryRus: 'Мозамбик',
  },
  {
    cca2: 'MR',
    country: 'Mauritania',
    flag: '🇲🇷',
    countryRus: 'Мавритания',
  },
  {
    cca2: 'MS',
    country: 'Montserrat',
    flag: '🇲🇸',
    countryRus: 'Монтсеррат',
  },
  {
    cca2: 'MQ',
    country: 'Martinique',
    flag: '🇲🇶',
    countryRus: 'Мартиника',
  },
  {
    cca2: 'MU',
    country: 'Mauritius',
    flag: '🇲🇺',
    countryRus: 'Маврикий',
  },
  {
    cca2: 'MW',
    country: 'Malawi',
    flag: '🇲🇼',
    countryRus: 'Малави',
  },
  {
    cca2: 'MY',
    country: 'Malaysia',
    flag: '🇲🇾',
    countryRus: 'Малайзия',
  },
  {
    cca2: 'YT',
    country: 'Mayotte',
    flag: '🇾🇹',
    countryRus: 'Майотта',
  },
  {
    cca2: 'NA',
    country: 'Namibia',
    flag: '🇳🇦',
    countryRus: 'Намибия',
  },
  {
    cca2: 'NC',
    country: 'New Caledonia',
    flag: '🇳🇨',
    countryRus: 'Новая Каледония',
  },
  {
    cca2: 'NE',
    country: 'Niger',
    flag: '🇳🇪',
    countryRus: 'Нигер',
  },
  {
    cca2: 'NF',
    country: 'Norfolk Island',
    flag: '🇳🇫',
    countryRus: 'о-в Норфолк',
  },
  {
    cca2: 'NG',
    country: 'Nigeria',
    flag: '🇳🇬',
    countryRus: 'Нигерия',
  },
  {
    cca2: 'NI',
    country: 'Nicaragua',
    flag: '🇳🇮',
    countryRus: 'Никарагуа',
  },
  {
    cca2: 'NU',
    country: 'Niue',
    flag: '🇳🇺',
    countryRus: 'Ниуэ',
  },
  {
    cca2: 'NL',
    country: 'Netherlands',
    flag: '🇳🇱',
    countryRus: 'Нидерланды',
  },
  {
    cca2: 'NO',
    country: 'Norway',
    flag: '🇳🇴',
    countryRus: 'Норвегия',
  },
  {
    cca2: 'NP',
    country: 'Nepal',
    flag: '🇳🇵',
    countryRus: 'Непал',
  },
  {
    cca2: 'NR',
    country: 'Nauru',
    flag: '🇳🇷',
    countryRus: 'Науру',
  },
  {
    cca2: 'NZ',
    country: 'New Zealand',
    flag: '🇳🇿',
    countryRus: 'Новая Зеландия',
  },
  {
    cca2: 'OM',
    country: 'Oman',
    flag: '🇴🇲',
    countryRus: 'Оман',
  },
  {
    cca2: 'PK',
    country: 'Pakistan',
    flag: '🇵🇰',
    countryRus: 'Пакистан',
  },
  {
    cca2: 'PA',
    country: 'Panama',
    flag: '🇵🇦',
    countryRus: 'Панама',
  },
  {
    cca2: 'PN',
    country: 'Pitcairn Islands',
    flag: '🇵🇳',
    countryRus: 'о-ва Питкэрн',
  },
  {
    cca2: 'PE',
    country: 'Peru',
    flag: '🇵🇪',
    countryRus: 'Перу',
  },
  {
    cca2: 'PH',
    country: 'Philippines',
    flag: '🇵🇭',
    countryRus: 'Филиппины',
  },
  {
    cca2: 'PW',
    country: 'Palau',
    flag: '🇵🇼',
    countryRus: 'Палау',
  },
  {
    cca2: 'PG',
    country: 'Papua New Guinea',
    flag: '🇵🇬',
    countryRus: 'Папуа — Новая Гвинея',
  },
  {
    cca2: 'PL',
    country: 'Poland',
    flag: '🇵🇱',
    countryRus: 'Польша',
  },
  {
    cca2: 'PR',
    country: 'Puerto Rico',
    flag: '🇵🇷',
    countryRus: 'Пуэрто-Рико',
  },
  {
    cca2: 'KP',
    country: 'North Korea',
    flag: '🇰🇵',
    countryRus: 'КНДР',
  },
  {
    cca2: 'PT',
    country: 'Portugal',
    flag: '🇵🇹',
    countryRus: 'Португалия',
  },
  {
    cca2: 'PY',
    country: 'Paraguay',
    flag: '🇵🇾',
    countryRus: 'Парагвай',
  },
  {
    cca2: 'PS',
    country: 'Palestine',
    flag: '🇵🇸',
    countryRus: 'Палестина',
  },
  {
    cca2: 'PF',
    country: 'French Polynesia',
    flag: '🇵🇫',
    countryRus: 'Французская Полинезия',
  },
  {
    cca2: 'QA',
    country: 'Qatar',
    flag: '🇶🇦',
    countryRus: 'Катар',
  },
  {
    cca2: 'RE',
    country: 'Réunion',
    flag: '🇷🇪',
    countryRus: 'Реюньон',
  },
  {
    cca2: 'RO',
    country: 'Romania',
    flag: '🇷🇴',
    countryRus: 'Румыния',
  },
  {
    cca2: 'RU',
    country: 'Russia',
    flag: '🇷🇺',
    countryRus: 'Россия',
  },
  {
    cca2: 'RW',
    country: 'Rwanda',
    flag: '🇷🇼',
    countryRus: 'Руанда',
  },
  {
    cca2: 'SA',
    country: 'Saudi Arabia',
    flag: '🇸🇦',
    countryRus: 'Саудовская Аравия',
  },
  {
    cca2: 'SD',
    country: 'Sudan',
    flag: '🇸🇩',
    countryRus: 'Судан',
  },
  {
    cca2: 'SN',
    country: 'Senegal',
    flag: '🇸🇳',
    countryRus: 'Сенегал',
  },
  {
    cca2: 'SG',
    country: 'Singapore',
    flag: '🇸🇬',
    countryRus: 'Сингапур',
  },
  {
    cca2: 'GS',
    country: 'South Georgia',
    flag: '🇬🇸',
    countryRus: 'Южная Георгия и Южные Сандвичевы о-ва',
  },
  {
    cca2: 'SJ',
    country: 'Svalbard and Jan Mayen',
    flag: '🇸🇯',
    countryRus: 'Шпицберген и Ян-Майен',
  },
  {
    cca2: 'SB',
    country: 'Solomon Islands',
    flag: '🇸🇧',
    countryRus: 'Соломоновы о-ва',
  },
  {
    cca2: 'SL',
    country: 'Sierra Leone',
    flag: '🇸🇱',
    countryRus: 'Сьерра-Леоне',
  },
  {
    cca2: 'SV',
    country: 'El Salvador',
    flag: '🇸🇻',
    countryRus: 'Сальвадор',
  },
  {
    cca2: 'SM',
    country: 'San Marino',
    flag: '🇸🇲',
    countryRus: 'Сан-Марино',
  },
  {
    cca2: 'SO',
    country: 'Somalia',
    flag: '🇸🇴',
    countryRus: 'Сомали',
  },
  {
    cca2: 'PM',
    country: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
    countryRus: 'Сен-Пьер и Микелон',
  },
  {
    cca2: 'RS',
    country: 'Serbia',
    flag: '🇷🇸',
    countryRus: 'Сербия',
  },
  {
    cca2: 'SS',
    country: 'South Sudan',
    flag: '🇸🇸',
    countryRus: 'Южный Судан',
  },
  {
    cca2: 'ST',
    country: 'São Tomé and Príncipe',
    flag: '🇸🇹',
    countryRus: 'Сан-Томе и Принсипи',
  },
  {
    cca2: 'SR',
    country: 'Suricountry',
    flag: '🇸🇷',
    countryRus: 'Суринам',
  },
  {
    cca2: 'SK',
    country: 'Slovakia',
    flag: '🇸🇰',
    countryRus: 'Словакия',
  },
  {
    cca2: 'SI',
    country: 'Slovenia',
    flag: '🇸🇮',
    countryRus: 'Словения',
  },
  {
    cca2: 'SE',
    country: 'Sweden',
    flag: '🇸🇪',
    countryRus: 'Швеция',
  },
  {
    cca2: 'SZ',
    country: 'Eswatini',
    flag: '🇸🇿',
    countryRus: 'Эсватини',
  },
  {
    cca2: 'SX',
    country: 'Sint Maarten',
    flag: '🇸🇽',
    countryRus: 'Синт-Мартен',
  },
  {
    cca2: 'SC',
    country: 'Seychelles',
    flag: '🇸🇨',
    countryRus: 'Сейшельские о-ва',
  },
  {
    cca2: 'SY',
    country: 'Syria',
    flag: '🇸🇾',
    countryRus: 'Сирия',
  },
  {
    cca2: 'TC',
    country: 'Turks and Caicos Islands',
    flag: '🇹🇨',
    countryRus: 'Тёркс и Кайкос',
  },
  {
    cca2: 'TD',
    country: 'Chad',
    flag: '🇹🇩',
    countryRus: 'Чад',
  },
  {
    cca2: 'TG',
    country: 'Togo',
    flag: '🇹🇬',
    countryRus: 'Того',
  },
  {
    cca2: 'TH',
    country: 'Thailand',
    flag: '🇹🇭',
    countryRus: 'Таиланд',
  },
  {
    cca2: 'TJ',
    country: 'Tajikistan',
    flag: '🇹🇯',
    countryRus: 'Таджикистан',
  },
  {
    cca2: 'TK',
    country: 'Tokelau',
    flag: '🇹🇰',
    countryRus: 'Токелау',
  },
  {
    cca2: 'TM',
    country: 'Turkmenistan',
    flag: '🇹🇲',
    countryRus: 'Туркменистан',
  },
  {
    cca2: 'TL',
    country: 'Timor-Leste',
    flag: '🇹🇱',
    countryRus: 'Восточный Тимор',
  },
  {
    cca2: 'TO',
    country: 'Tonga',
    flag: '🇹🇴',
    countryRus: 'Тонга',
  },
  {
    cca2: 'TT',
    country: 'Trinidad and Tobago',
    flag: '🇹🇹',
    countryRus: 'Тринидад и Тобаго',
  },
  {
    cca2: 'TN',
    country: 'Tunisia',
    flag: '🇹🇳',
    countryRus: 'Тунис',
  },
  {
    cca2: 'TR',
    country: 'Türkiye',
    flag: '🇹🇷',
    countryRus: 'Турция',
  },
  {
    cca2: 'TV',
    country: 'Tuvalu',
    flag: '🇹🇻',
    countryRus: 'Тувалу',
  },
  {
    cca2: 'TW',
    country: 'Taiwan',
    flag: '🇹🇼',
    countryRus: 'Тайвань',
  },
  {
    cca2: 'TZ',
    country: 'Tanzania',
    flag: '🇹🇿',
    countryRus: 'Танзания',
  },
  {
    cca2: 'UG',
    country: 'Uganda',
    flag: '🇺🇬',
    countryRus: 'Уганда',
  },
  {
    cca2: 'UA',
    country: 'Ukraine',
    flag: '🇺🇦',
    countryRus: 'Украина',
  },
  {
    cca2: 'UM',
    country: 'United States Minor Outlying Islands',
    flag: '🇺🇲',
    countryRus: 'Внешние малые о-ва (США)',
  },
  {
    cca2: 'UY',
    country: 'Uruguay',
    flag: '🇺🇾',
    countryRus: 'Уругвай',
  },
  {
    cca2: 'US',
    country: 'United States',
    flag: '🇺🇸',
    countryRus: 'Соединенные Штаты',
  },
  {
    cca2: 'UZ',
    country: 'Uzbekistan',
    flag: '🇺🇿',
    countryRus: 'Узбекистан',
  },
  {
    cca2: 'VA',
    country: 'Vatican City',
    flag: '🇻🇦',
    countryRus: 'Ватикан',
  },
  {
    cca2: 'VC',
    country: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
    countryRus: 'Сент-Винсент и Гренадины',
  },
  {
    cca2: 'VE',
    country: 'Venezuela',
    flag: '🇻🇪',
    countryRus: 'Венесуэла',
  },
  {
    cca2: 'VG',
    country: 'British Virgin Islands',
    flag: '🇻🇬',
    countryRus: 'Виргинские о-ва (Великобритания)',
  },
  {
    cca2: 'VI',
    country: 'United States Virgin Islands',
    flag: '🇻🇮',
    countryRus: 'Виргинские о-ва (США)',
  },
  {
    cca2: 'VN',
    country: 'Vietnam',
    flag: '🇻🇳',
    countryRus: 'Вьетнам',
  },
  {
    cca2: 'VU',
    country: 'Vanuatu',
    flag: '🇻🇺',
    countryRus: 'Вануату',
  },
  {
    cca2: 'WF',
    country: 'Wallis and Futuna',
    flag: '🇼🇫',
    countryRus: 'Уоллис и Футуна',
  },
  {
    cca2: 'WS',
    country: 'Samoa',
    flag: '🇼🇸',
    countryRus: 'Самоа',
  },
  {
    cca2: 'YE',
    country: 'Yemen',
    flag: '🇾🇪',
    countryRus: 'Йемен',
  },
  {
    cca2: 'ZA',
    country: 'South Africa',
    flag: '🇿🇦',
    countryRus: 'Южно-Африканская Республика',
  },
  {
    cca2: 'ZM',
    country: 'Zambia',
    flag: '🇿🇲',
    countryRus: 'Замбия',
  },
  {
    cca2: 'ZW',
    country: 'Zimbabwe',
    flag: '🇿🇼',
    countryRus: 'Зимбабве',
  },
];
